AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack 4: CI/CD Pipeline (CodeDeploy, CodePipeline)"

Parameters:
  ApplicationName:
    Type: String
    Default: myapp
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production
    Description: Environment name (staging or production)

Conditions:
  IsProduction: !Equals [!Ref Environment, production]

Resources:
  # ==========================================
  # CodeDeploy
  # ==========================================
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Sub ${ApplicationName}-${Environment}
      ComputePlatform: Server

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: !Sub ${ApplicationName}-${Environment}-dg
      ServiceRoleArn:
        Fn::ImportValue: !Sub ${Environment}-CodeDeployRoleArn
      # Production: OneAtATime (safe, zero-downtime)
      # Staging: AllAtOnce (fast deployment for testing)
      DeploymentConfigName: !If
        - IsProduction
        - CodeDeployDefault.OneAtATime
        - CodeDeployDefault.AllAtOnce
      AutoScalingGroups:
        - Fn::ImportValue: !Sub ${Environment}-ASGName
      LoadBalancerInfo:
        TargetGroupInfoList:
          - Name:
              Fn::ImportValue: !Sub ${Environment}-TargetGroupName
      # Automatic rollback on any deployment failure
      # Triggers when any lifecycle hook fails (stop, install, start, validate)
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE

  # ==========================================
  # CodePipeline
  # ==========================================
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${ApplicationName}-${Environment}-pipeline
      RoleArn:
        Fn::ImportValue: !Sub ${Environment}-CodePipelineRoleArn
      ArtifactStore:
        Type: S3
        Location:
          Fn::ImportValue: !Sub ${Environment}-PipelineBucketName
      Stages:
        - Name: Source
          Actions:
            - Name: S3Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: "1"
              Configuration:
                S3Bucket:
                  Fn::ImportValue: !Sub ${Environment}-ArtifactsBucketName
                # Note: This key must match what GitHub Actions uploads
                S3ObjectKey: !Sub ${Environment}/${ApplicationName}-${Environment}.zip
                PollForSourceChanges: "false"
              OutputArtifacts:
                - Name: SourceOutput
        - !If
          - IsProduction
          - Name: Approve
            Actions:
              - Name: ManualApproval
                ActionTypeId:
                  Category: Approval
                  Owner: AWS
                  Provider: Manual
                  Version: "1"
                RunOrder: 1
          - !Ref AWS::NoValue
        - Name: Deploy
          Actions:
            - Name: CodeDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: "1"
              Configuration:
                ApplicationName: !Ref CodeDeployApplication
                DeploymentGroupName: !Ref CodeDeployDeploymentGroup
              InputArtifacts:
                - Name: SourceOutput

Outputs:
  PipelineUrl:
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/codesuite/codepipeline/pipelines/${Pipeline}/view
    Description: URL of the created CodePipeline
